# Use an official Python runtime as a parent image
FROM python:3.8-slim-buster

# Set the working directory in the container to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 8084 available to the world outside this container
EXPOSE 8084

# Define environment variable
ENV NAME Checkpointer

# Run app.py when the container launches
CMD ["uvicorn", "checkpointer:app", "--host", "0.0.0.0", "--port", "8084"]